version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 15
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 15
    schedule:
      interval: daily
