
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - discovery.eurek8s.com
  resources:
  - eurekaapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.eurek8s.com
  resources:
  - eurekaapplications/finalizers
  verbs:
  - update
- apiGroups:
  - discovery.eurek8s.com
  resources:
  - eurekaapplications/status
  verbs:
  - get
  - patch
  - update
