name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
#  release:
#    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5' # The Go version to download (if necessary) and use.

      - name: Build
        run: make docker-build IMG=eurek8s/controller:latest-main

      - name: Log in to Docker Hub
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          username: ${{ secrets.DOCKER_HUB__USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Publish Image
        run: make docker-push IMG=eurek8s/controller:latest-main