name: Publish image
on:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Show version
        run:
          echo "Building version ${{ steps.get_version.outputs.VERSION }}"

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5' # The Go version to download (if necessary) and use.

      - name: Log in to Docker Hub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build
        run: make docker-build IMG=eurek8s/controller:${{ steps.get_version.outputs.VERSION }}

      - name: Publish Image
        run: make docker-push IMG=eurek8s/controller:${{ steps.get_version.outputs.VERSION }}