name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
#  release:
#    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make docker-build IMG=ghcr.io/Eurek8s/eurek8s-controller:latest-main

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5' # The Go version to download (if necessary) and use.

      - name: Publish Image
        run: make docker-push IMG=ghcr.io/Eurek8s/eurek8s-controller:latest-main